#!/bin/bash

get_local_ip() {
    local_ip_interface=(auto)
    interface=$1
    [ -n "${interface}" ] && local_ip_interface=''
    if [ "$(uname -o)" = "GNU/Linux" ]; then
        if [[ "${local_ip_interface[0]}" == "auto" ]]; then
            local_ip="$(ip route get 1 | awk -F'src' '{print $2; exit}')"
            local_ip="${local_ip/uid*}"
            [ -z "$local_ip" ] && local_ip="$(ifconfig -a | awk '/broadcast/ {print $2; exit}')"
            echo ${local_ip}
        else
            local_ip="$(ip addr show "$interface" 2> /dev/null | awk '/inet / {print $2; exit}')"
            local_ip="${local_ip/\/*}"
            [ -z "$local_ip" ] && local_ip="$(ifconfig "$interface" 2> /dev/null | awk '/broadcast/ {print $2; exit}')"
            if [[ -n "$local_ip" ]]; then
                echo "$local_ip"
            else
                echo "Local IP: Could not detect local ip for $interface"
                return 1
            fi
        fi
    else
        # "Mac OS X" | "macOS" | "iPhone OS")
        if [[ "${local_ip_interface[0]}" == "auto" ]]; then
            interface="$(route get 1 | awk -F': ' '/interface/ {printf $2; exit}')"
            local_ip="$(ipconfig getifaddr "$interface")"
            echo $local_ip
        else
            for interface in "${local_ip_interface[@]}"; do
                local_ip="$(ipconfig getifaddr "$interface")"
                if [[ -n "$local_ip" ]]; then
                    echo "$local_ip"
                else
                    echo "Local IP: Could not detect local ip for $interface"
                    return 1
                fi
            done
        fi
    fi
}

get_public_ip() {
    public_ip_host="http://ident.me"
    public_ip_timeout=2
    if [[ ! -n "$public_ip_host" ]] && type -p dig >/dev/null; then
        public_ip="$(dig +time=1 +tries=1 +short myip.opendns.com @resolver1.opendns.com)"
       [[ "$public_ip" =~ ^\; ]] && unset public_ip
    fi

    if [[ ! -n "$public_ip_host" ]] && [[ -z "$public_ip" ]] && type -p drill >/dev/null; then
        public_ip="$(drill myip.opendns.com @resolver1.opendns.com | awk '/^myip\./ && $3 == "IN" {print $5}')"
    fi

    if [[ -z "$public_ip" ]] && type -p curl >/dev/null; then
        public_ip="$(curl -s -L --max-time "$public_ip_timeout" -w '\n' "$public_ip_host")"
    fi

    if [[ -z "$public_ip" ]] && type -p wget >/dev/null; then
        public_ip="$(wget -T "$public_ip_timeout" -qO- "$public_ip_host")"
    fi
    echo $public_ip
}

localip=$(get_local_ip $1)
if [ $# -gt 1 ] ; then
    echo -n ${localip} ' '
    get_public_ip
else
    echo ${localip}
fi
